# Generated by Django 4.0.6 on 2022-07-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacion', '0001_CreacionUsuarioModel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
