# Generated by Django 4.0.6 on 2022-07-15 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_CreacionTablaTareas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-fechaVencimiento']},
        ),
        migrations.AlterModelTable(
            name='tarea',
            table='tareas',
        ),
    ]
