# Generated by Django 4.0.6 on 2022-07-16 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0002_renombre_tabla_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='usuarioId',
            field=models.ForeignKey(db_column='usuario_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
